// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const getTokens = `-- name: GetTokens :many
SELECT
    id, type, expires_at, created_at, updated_at
FROM
    access_tokens
`

func (q *Queries) GetTokens(ctx context.Context) ([]AccessToken, error) {
	rows, err := q.db.Query(ctx, getTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessToken
	for rows.Next() {
		var i AccessToken
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
